{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "artifactory.fullname" . -}}
{{- $servicePort := .Values.artifactory.externalPort -}}
{{- $artifactoryServicePort := .Values.artifactory.externalArtifactoryPort -}}
{{- $ingressName := default ( include "artifactory.fullname" . ) .Values.ingress.name -}}
{{- $apiVersion := include "ingress.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    app: {{ template "artifactory.name" . }}
    chart: {{ template "artifactory.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ .Values.ingress.labels | toYaml | trimSuffix "\n"| indent 4 -}}
{{- end}}
{{- if .Values.ingress.annotations }}
  annotations:
{{ .Values.ingress.annotations | toYaml | trimSuffix "\n" | indent 4 -}}
{{- end }}
spec:
  {{- if .Values.ingress.defaultBackend.enabled }}
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ $servicePort }}
  {{- end }}
  rules:
{{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host | quote }}
    http:
      paths:
        - path: {{ $.Values.ingress.routerPath }}
          backend:
            {{- if or (eq $apiVersion "extensions/v1beta1") (eq $apiVersion "networking.k8s.io/v1beta1") -}}
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
            {{- else -}}
            service:
              name: {{ $serviceName }}
              port:
                {{- if typeIs "string" $servicePort }}
                name: {{ $servicePort }}
                {{- else if or (typeIs "int" $servicePort) (typeIs "float64" $servicePort) }}
                number: {{ $servicePort | int }}
                {{- end }}
            {{- end -}}
        - path: {{ $.Values.ingress.artifactoryPath }}
          backend:
            {{- if or (eq $apiVersion "extensions/v1beta1") (eq $apiVersion "networking.k8s.io/v1beta1") -}}
            serviceName: {{ $serviceName }}
            servicePort: {{ $artifactoryServicePort }}
            {{- else -}}
            service:
              name: {{ $serviceName }}
              port:
                {{- if typeIs "string" $artifactoryServicePort }}
                name: {{ $artifactoryServicePort }}
                {{- else if or (typeIs "int" $artifactoryServicePort) (typeIs "float64" $artifactoryServicePort) }}
                number: {{ $artifactoryServicePort | int }}
                {{- end }}
            {{- end -}}
  {{- end -}}
{{- end -}}
  {{- with .Values.ingress.additionalRules }}
{{ tpl . $ | indent 2 }}
  {{- end }}

  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- if .Values.artifactory.replicator.enabled }}
---
{{- $replicatorIngressName := default ( include "artifactory.replicator.fullname" . ) .Values.artifactory.replicator.ingress.name -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ $replicatorIngressName }}
  labels:
    app: "{{ template "artifactory.name" $ }}"
    chart: "{{ template "artifactory.chart" $ }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
  {{- if .Values.artifactory.replicator.ingress.annotations }}
  annotations:
{{ .Values.artifactory.replicator.ingress.annotations | toYaml | trimSuffix "\n" | indent 4 -}}
  {{- end }}
spec:
  {{- if .Values.ingress.defaultBackend.enabled }}
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ $servicePort }}
  {{- end }}
  rules:
{{- if .Values.artifactory.replicator.ingress.hosts }}
  {{- range $host := .Values.artifactory.replicator.ingress.hosts }}
  - host: {{ $host | quote }}
    http:
      paths:
        - path: /replicator/
          backend:
            {{- if or (eq $apiVersion "extensions/v1beta1") (eq $apiVersion "networking.k8s.io/v1beta1") -}}
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
            {{- else -}}
            service:
              name: {{ $serviceName }}
              port:
                {{- if typeIs "string" $servicePort }}
                name: {{ $servicePort }}
                {{- else if or (typeIs "int" $servicePort) (typeIs "float64" $servicePort) }}
                number: {{ $servicePort | int }}
                {{- end }}
            {{- end -}}
        - path: /artifactory/api/replication/replicate/file/streaming
          backend:
            {{- if or (eq $apiVersion "extensions/v1beta1") (eq $apiVersion "networking.k8s.io/v1beta1") -}}
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
            {{- else -}}
            service:
              name: {{ $serviceName }}
              port:
                {{- if typeIs "string" $servicePort }}
                name: {{ $servicePort }}
                {{- else if or (typeIs "int" $servicePort) (typeIs "float64" $servicePort) }}
                number: {{ $servicePort | int }}
                {{- end }}
            {{- end -}}
  {{- end -}}
{{- end -}}
  {{- if .Values.artifactory.replicator.ingress.tls }}
  tls:
{{ toYaml .Values.artifactory.replicator.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- if and .Values.artifactory.replicator.enabled .Values.artifactory.replicator.trackerIngress.enabled }}
---
{{- $replicatorTrackerIngressName := default ( include "artifactory.replicator.tracker.fullname" . ) .Values.artifactory.replicator.trackerIngress.name -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ $replicatorTrackerIngressName }}
  labels:
    app: "{{ template "artifactory.name" $ }}"
    chart: "{{ template "artifactory.chart" $ }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
  {{- if .Values.artifactory.replicator.trackerIngress.annotations }}
  annotations:
{{ .Values.artifactory.replicator.trackerIngress.annotations | toYaml | trimSuffix "\n" | indent 4 -}}
  {{- end }}
spec:
  {{- if .Values.ingress.defaultBackend.enabled }}
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ $servicePort }}
  {{- end }}
  rules:
{{- if .Values.artifactory.replicator.trackerIngress.hosts }}
  {{- range $host := .Values.artifactory.replicator.trackerIngress.hosts }}
  - host: {{ $host | quote }}
    http:
      paths:
        - path: /
          backend:
            {{- if or (eq $apiVersion "extensions/v1beta1") (eq $apiVersion "networking.k8s.io/v1beta1") -}}
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
            {{- else -}}
            service:
              name: {{ $serviceName }}
              port:
                {{- if typeIs "string" $servicePort }}
                name: {{ $servicePort }}
                {{- else if or (typeIs "int" $servicePort) (typeIs "float64" $servicePort) }}
                number: {{ $servicePort | int }}
                {{- end }}
            {{- end -}}
  {{- end -}}
{{- end -}}
  {{- if .Values.artifactory.replicator.trackerIngress.tls }}
  tls:
{{ toYaml .Values.artifactory.replicator.trackerIngress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- if .Values.customIngress }}
---
{{ .Values.customIngress | toYaml | trimSuffix "\n" }}
{{- end -}}
{{- end -}}
